# apiVersion: extensions/v1beta1
#Above is for 1.5 or?
#For k8s 1.7,apps/v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-mysql
  labels:
    app: spring-mysql-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-mysql-example 
  template:
    metadata:
      labels:
        app: spring-mysql-example
    spec:
      containers:
      - name: spring-mysql
        image: 10.1.0.7:3333/spring-mysql:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regcred
